// ── DATA ──────────────────────────────────────────────────────────
const locations = {
embankment: {
id: "embankment",
title: "Irtysh Embankment",
subtitle: "Набережная Иртыша • Ертіс жағалауы",
icon: "🌊",
image: "assets/embankment.jpg",
lat: 52.2868,
lng: 76.9673,
text: [
{en: "The", ru: "Определённый артикль", kz: "Белгілі артикль"},
{en: "Irtysh", ru: "Иртыш", kz: "Ертіс"},
{en: "Embankment", ru: "набережная", kz: "жағалау"},
{en: "is", ru: "является", kz: "болып табылады"},
{en: "the", ru: "самое", kz: "ең"},
{en: "heart", ru: "сердце", kz: "жүрек"},
{en: "of", ru: "города", kz: "қаланың"},
{en: "Pavlodar.", ru: "Павлодара.", kz: "Павлодардың."},
{en: "break"},
{en: "People", ru: "Люди", kz: "Адамдар"},
{en: "come", ru: "приходят", kz: "келеді"},
{en: "here", ru: "сюда", kz: "мұнда"},
{en: "to", ru: "чтобы", kz: "үшін"},
{en: "walk,", ru: "гулять,", kz: "серуендеу,"},
{en: "ride", ru: "кататься", kz: "міну"},
{en: "bikes", ru: "на велосипедах", kz: "велосипедпен"},
{en: "and", ru: "и", kz: "және"},
{en: "watch", ru: "смотреть", kz: "қарау"},
{en: "the", ru: "на", kz: ""},
{en: "sunset.", ru: "закат.", kz: "күн батысын."},
 ]
},
mashkhur: {
id: "mashkhur",
title: "Mashkhur Zhusup Mosque",
subtitle: "Мечеть Машхур Жусупа • Мешіт",
icon: "🕌",
image: "assets/mosque.jpg",
lat: 52.2980,
lng: 76.9461,
text: [
{en: "The", ru: "Определённый артикль", kz: "Белгілі артикль"},
{en: "mosque", ru: "мечеть", kz: "мешіт"},
{en: "is", ru: "является", kz: "болып табылады"},
{en: "a", ru: "красивым", kz: "әдемі"},
{en: "beautiful", ru: "красивым", kz: "әдемі"},
{en: "building", ru: "зданием", kz: "ғимарат"},
{en: "in", ru: "в", kz: "орналасқан"},
{en: "the", ru: "в", kz: ""},
{en: "city.", ru: "городе.", kz: "қалада."},
{en: "break"},
{en: "It", ru: "Оно", kz: "Ол"},
{en: "has", ru: "имеет", kz: "бар"},
{en: "a", ru: "", kz: ""},
{en: "large", ru: "большой", kz: "үлкен"},
{en: "blue", ru: "синий", kz: "көк"},
{en: "dome.", ru: "купол.", kz: "күмбез."},
 ]
},
park: {
id: "park",
title: "City Park & Lake",
subtitle: "Центральный парк • Орталық саябақ",
icon: "🌳",
image: "assets/park.jpg",
lat: 52.2924,
lng: 76.9510,
text: [
{en: "The", ru: "Определённый артикль", kz: "Белгілі артикль"},
{en: "park", ru: "парк", kz: "саябақ"},
{en: "has", ru: "имеет", kz: "бар"},
{en: "a", ru: "", kz: ""},
{en: "beautiful", ru: "красивое", kz: "әдемі"},
{en: "lake.", ru: "озеро.", kz: "көл."},
{en: "break"},
{en: "Children", ru: "Дети", kz: "Балалар"},
{en: "play", ru: "играют", kz: "ойнайды"},
{en: "here", ru: "здесь", kz: "мұнда"},
{en: "every", ru: "каждый", kz: "әр"},
{en: "day.", ru: "день.", kz: "күні."},
 ]
},
museum: {
id: "museum",
title: "Regional Museum",
subtitle: "Краеведческий музей • Өлкетану мұражайы",
icon: "🏛️",
image: "assets/museum.jpg",
lat: 52.2851,
lng: 76.9402,
text: [
{en: "The", ru: "Определённый артикль", kz: "Белгілі артикль"},
{en: "museum", ru: "музей", kz: "мұражай"},
{en: "tells", ru: "рассказывает", kz: "айтады"},
{en: "the", ru: "", kz: ""},
{en: "history", ru: "историю", kz: "тарихын"},
{en: "of", ru: "города.", kz: "қаланың."},
{en: "Pavlodar.", ru: "Павлодара.", kz: "Павлодардың."},
{en: "break"},
{en: "You", ru: "Вы", kz: "Сіз"},
{en: "can", ru: "можете", kz: "болады"},
{en: "see", ru: "увидеть", kz: "көруге"},
{en: "old", ru: "старые", kz: "ескі"},
{en: "photos", ru: "фотографии", kz: "фотосуреттер"},
{en: "and", ru: "и", kz: "және"},
{en: "artifacts.", ru: "артефакты.", kz: "артефактілер."},
 ]
}
};
